pipeline:
  name: chaos-onboarding-pipeline
  identifier: chaosonboardingpipeline
  projectIdentifier: ChaosDev
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: "onboard chaos "
        identifier: onboard_chaos
        template:
          templateRef: uaonboardpipeline
          versionLabel: 0.1.0
  variables:
    - name: HARNESS_API_KEY
      type: Secret
      description: ""
      required: false
      value: harness_pat_token_onboard
    - name: ORGANISATION_ID
      type: String
      default: onboardtrial
      description: ""
      required: false
      value: <+input>
    - name: ACCOUNT_ID
      type: String
      default: cTU1lRSWS2SSRV9phKvuOA
      description: ""
      required: false
      value: <+input>
    - name: PROJECT_ID
      type: String
      default: ChaosDev
      description: Project ID
      required: true
      value: <+input>
    - name: INFRA_NAMESPACE_DEV
      type: String
      default: app1-dev
      description: Infra namespace for dev
      required: false
      value: <+input>
    - name: INFRA_NAME_DEV
      type: String
      default: app1-dev
      description: Infra name for dev
      required: false
      value: <+input>
    - name: INFRA_NAME_STAGING
      type: String
      default: app1-stg
      description: Infra name for staging
      required: false
      value: <+input>
    - name: INFRA_NAMESPACE_STAGING
      type: String
      default: app1-stg
      description: Infra namespace for staging
      required: false
      value: <+input>
    - name: ONBOARDING_NAMESPACE
      type: String
      default: default
      description: Onboarding namespace
      required: false
      value: <+input>
    - name: ONBOARDING_SERVICE_ACCOUNT_NAME
      type: String
      description: Onboarding service account name
      required: false
      value: <+input>
      default: chaos-onboard-util
    - name: AWS_ACCESS_KEY_ID
      type: Secret
      description: ""
      required: false
      value: ONBOARD_AWS_ACCESS_KEY_ID
    - name: AWS_SECRET_ACCESS_KEY
      type: Secret
      description: ""
      required: false
      value: ONBOARD_AWS_SECRET_ACCESS_KEY
    - name: CHAOSHUB_NAME
      type: String
      default: Enterprise ChaosHub
      description: ""
      required: false
      value: <+input>
    - name: PREDEFINED_EXPERIMENT
      type: String
      default: rds
      description: ""
      required: false
      value: <+input>
